"""
10-seed paired repeated-split robustness comparison:

78D signal-derived-with-ground descriptors
    Ridge
        vs
    RBF-SVR

Protocol
--------
- Use all 3000 cases.
- Ten deterministic random 70/15/15 splits.
- Feature standardisation is re-fitted on EACH seed's training fold only.
- Ridge and SVR use exactly the same split within each seed.
- Hyperparameters are selected by clipped validation MSE only.
- Test is evaluated only after validation selection.
- Predictions are clipped to [0, 0.5].
- SVR uses the previously frozen 75-candidate search grid.

This experiment is separate from the historical fixed-split protocol.
Do not numerically mix fixed-split and repeated-split metrics as though
they were generated by the same evaluation design.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
import time
from typing import Any

import numpy as np
import pandas as pd
from scipy.stats import t as student_t
from scipy.stats import ttest_rel, wilcoxon
from sklearn.linear_model import Ridge
from sklearn.multioutput import MultiOutputRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR


EXPECTED_FEATURE_COUNT = 78
EXPECTED_CASE_COUNT = 3000

SEEDS = list(range(10))

N_TRAIN = 2100
N_VAL = 450
N_TEST = 450

RIDGE_ALPHAS = [
    1e-6,
    3e-6,
    1e-5,
    3e-5,
    1e-4,
    3e-4,
    1e-3,
    3e-3,
    1e-2,
    3e-2,
    1e-1,
    1.0,
    10.0,
    100.0,
    300.0,
]

SVR_C_VALUES = [
    100.0,
    300.0,
    500.0,
    750.0,
    1000.0,
]

SVR_GAMMA_VALUES = [
    0.0005,
    0.00075,
    0.001,
    0.003,
    0.01,
]

SVR_EPSILON_VALUES = [
    0.02,
    0.03,
    0.04,
]

PRIMARY_METRICS = [
    "test_mae",
    "test_rmse",
    "damaged_entry_mae",
    "zero_damage_mae",
    "high_damage_mae",
    "high_damage_abs_bias",
    "high_damage_underestimation_ratio",
]


def _numeric_array(
    data: Any,
    key: str,
) -> np.ndarray:
    return np.asarray(
        data[key],
        dtype=np.float64,
    )


def _find_feature_vector(
    data: Any,
    exact_names: list[str],
    keyword: str,
) -> tuple[str, np.ndarray] | None:
    """
    Find a 78-dimensional numeric mean/std vector.

    First try explicit common names; otherwise search numeric
    one-dimensional arrays whose name contains the keyword.
    """

    for key in exact_names:
        if key in data.files:
            array = np.asarray(data[key])

            if (
                array.ndim == 1
                and array.shape[0]
                == EXPECTED_FEATURE_COUNT
                and np.issubdtype(
                    array.dtype,
                    np.number,
                )
            ):
                return (
                    key,
                    np.asarray(
                        array,
                        dtype=np.float64,
                    ),
                )

    candidates = []

    for key in data.files:
        if keyword not in key.lower():
            continue

        try:
            array = np.asarray(data[key])
        except Exception:
            continue

        if (
            array.ndim == 1
            and array.shape[0]
            == EXPECTED_FEATURE_COUNT
            and np.issubdtype(
                array.dtype,
                np.number,
            )
        ):
            candidates.append(
                (
                    key,
                    np.asarray(
                        array,
                        dtype=np.float64,
                    ),
                )
            )

    if len(candidates) == 1:
        return candidates[0]

    return None


def load_full_raw_dataset(
    path: Path,
) -> tuple[
    np.ndarray,
    np.ndarray,
    dict[str, Any],
]:
    """
    Reconstruct the complete 3000-case raw 78D descriptor matrix.

    Preferred route:
        F_train_raw / F_val_raw / F_test_raw

    Fallback:
        invert the canonical standardisation using stored feature
        mean and standard deviation.

    We must NOT concatenate already-standardised F_train/F_val/F_test
    and directly random-split them, because that would preserve the
    original split's scaling and introduce preprocessing leakage.
    """

    if not path.is_file():
        raise FileNotFoundError(path)

    required = {
        "F_train",
        "F_val",
        "F_test",
        "y_train",
        "y_val",
        "y_test",
    }

    with np.load(
        path,
        allow_pickle=False,
    ) as data:

        missing = sorted(
            required - set(data.files)
        )

        if missing:
            raise KeyError(
                f"Missing required arrays: {missing}"
            )

        F_train = _numeric_array(
            data,
            "F_train",
        )
        F_val = _numeric_array(
            data,
            "F_val",
        )
        F_test = _numeric_array(
            data,
            "F_test",
        )

        y_train = _numeric_array(
            data,
            "y_train",
        )
        y_val = _numeric_array(
            data,
            "y_val",
        )
        y_test = _numeric_array(
            data,
            "y_test",
        )

        raw_keys = {
            "F_train_raw",
            "F_val_raw",
            "F_test_raw",
        }

        metadata: dict[str, Any] = {}

        if raw_keys.issubset(
            set(data.files)
        ):
            raw_train = _numeric_array(
                data,
                "F_train_raw",
            )
            raw_val = _numeric_array(
                data,
                "F_val_raw",
            )
            raw_test = _numeric_array(
                data,
                "F_test_raw",
            )

            reconstruction_mode = (
                "explicit_raw_arrays"
            )

        else:
            mean_result = (
                _find_feature_vector(
                    data,
                    exact_names=[
                        "feature_mean",
                        "feature_means",
                        "F_mean",
                        "train_feature_mean",
                        "mean",
                    ],
                    keyword="mean",
                )
            )

            std_result = (
                _find_feature_vector(
                    data,
                    exact_names=[
                        "feature_std",
                        "feature_stds",
                        "F_std",
                        "train_feature_std",
                        "std",
                    ],
                    keyword="std",
                )
            )

            if (
                mean_result is None
                or std_result is None
            ):
                raise RuntimeError(
                    "Could not recover raw descriptors. "
                    "Expected either F_*_raw arrays or "
                    "78-dimensional stored mean/std vectors.\n"
                    f"Available keys: {sorted(data.files)}"
                )

            mean_key, feature_mean = (
                mean_result
            )

            std_key, feature_std = (
                std_result
            )

            raw_train = (
                F_train
                * feature_std
                + feature_mean
            )

            raw_val = (
                F_val
                * feature_std
                + feature_mean
            )

            raw_test = (
                F_test
                * feature_std
                + feature_mean
            )

            reconstruction_mode = (
                "inverse_standardisation"
            )

            metadata[
                "mean_key"
            ] = mean_key

            metadata[
                "std_key"
            ] = std_key

    for name, array in {
        "F_train": F_train,
        "F_val": F_val,
        "F_test": F_test,
        "raw_train": raw_train,
        "raw_val": raw_val,
        "raw_test": raw_test,
        "y_train": y_train,
        "y_val": y_val,
        "y_test": y_test,
    }.items():
        if not np.all(
            np.isfinite(array)
        ):
            raise FloatingPointError(
                f"{name} contains non-finite values."
            )

    if (
        raw_train.shape
        != (
            N_TRAIN,
            EXPECTED_FEATURE_COUNT,
        )
    ):
        raise ValueError(
            f"Unexpected raw_train shape: "
            f"{raw_train.shape}"
        )

    if (
        raw_val.shape
        != (
            N_VAL,
            EXPECTED_FEATURE_COUNT,
        )
    ):
        raise ValueError(
            f"Unexpected raw_val shape: "
            f"{raw_val.shape}"
        )

    if (
        raw_test.shape
        != (
            N_TEST,
            EXPECTED_FEATURE_COUNT,
        )
    ):
        raise ValueError(
            f"Unexpected raw_test shape: "
            f"{raw_test.shape}"
        )

    x_full = np.vstack(
        [
            raw_train,
            raw_val,
            raw_test,
        ]
    )

    y_full = np.vstack(
        [
            y_train,
            y_val,
            y_test,
        ]
    )

    if (
        x_full.shape
        != (
            EXPECTED_CASE_COUNT,
            EXPECTED_FEATURE_COUNT,
        )
    ):
        raise ValueError(
            f"Unexpected full feature shape: "
            f"{x_full.shape}"
        )

    if (
        y_full.shape
        != (
            EXPECTED_CASE_COUNT,
            4,
        )
    ):
        raise ValueError(
            f"Unexpected full target shape: "
            f"{y_full.shape}"
        )

    metadata[
        "reconstruction_mode"
    ] = reconstruction_mode

    metadata[
        "n_cases"
    ] = int(
        x_full.shape[0]
    )

    metadata[
        "n_features"
    ] = int(
        x_full.shape[1]
    )

    return (
        x_full,
        y_full,
        metadata,
    )


def make_split(
    n_cases: int,
    seed: int,
) -> tuple[
    np.ndarray,
    np.ndarray,
    np.ndarray,
]:

    rng = np.random.default_rng(
        seed
    )

    permutation = rng.permutation(
        n_cases
    )

    train_idx = permutation[
        :N_TRAIN
    ]

    val_idx = permutation[
        N_TRAIN:
        N_TRAIN + N_VAL
    ]

    test_idx = permutation[
        N_TRAIN + N_VAL:
    ]

    if (
        len(train_idx) != N_TRAIN
        or len(val_idx) != N_VAL
        or len(test_idx) != N_TEST
    ):
        raise RuntimeError(
            "Split size check failed."
        )

    if (
        len(
            np.unique(
                np.concatenate(
                    [
                        train_idx,
                        val_idx,
                        test_idx,
                    ]
                )
            )
        )
        != n_cases
    ):
        raise RuntimeError(
            "Split overlap or omission detected."
        )

    return (
        train_idx,
        val_idx,
        test_idx,
    )


def clip_prediction(
    prediction: np.ndarray,
) -> np.ndarray:

    return np.clip(
        np.asarray(
            prediction,
            dtype=np.float64,
        ),
        0.0,
        0.5,
    )


def mse(
    truth: np.ndarray,
    prediction: np.ndarray,
) -> float:

    error = (
        np.asarray(prediction)
        - np.asarray(truth)
    )

    return float(
        np.mean(
            error ** 2
        )
    )


def mae(
    truth: np.ndarray,
    prediction: np.ndarray,
) -> float:

    return float(
        np.mean(
            np.abs(
                np.asarray(prediction)
                - np.asarray(truth)
            )
        )
    )


def calculate_metrics(
    truth: np.ndarray,
    prediction: np.ndarray,
) -> dict[str, float]:

    truth = np.asarray(
        truth,
        dtype=np.float64,
    )

    prediction = np.asarray(
        prediction,
        dtype=np.float64,
    )

    error = (
        prediction
        - truth
    )

    damaged = (
        truth > 1e-12
    )

    zero = (
        truth <= 1e-12
    )

    high = (
        truth > 0.20
    )

    if not np.any(
        damaged
    ):
        raise ValueError(
            "No damaged entries."
        )

    if not np.any(
        zero
    ):
        raise ValueError(
            "No zero-damage entries."
        )

    if not np.any(
        high
    ):
        raise ValueError(
            "No high-damage entries."
        )

    high_bias = float(
        np.mean(
            error[high]
        )
    )

    return {
        "test_mae": float(
            np.mean(
                np.abs(error)
            )
        ),
        "test_rmse": float(
            np.sqrt(
                np.mean(
                    error ** 2
                )
            )
        ),
        "test_bias": float(
            np.mean(error)
        ),
        "damaged_entry_mae": float(
            np.mean(
                np.abs(
                    error[damaged]
                )
            )
        ),
        "zero_damage_mae": float(
            np.mean(
                np.abs(
                    error[zero]
                )
            )
        ),
        "high_damage_mae": float(
            np.mean(
                np.abs(
                    error[high]
                )
            )
        ),
        "high_damage_bias": (
            high_bias
        ),
        "high_damage_abs_bias": (
            abs(
                high_bias
            )
        ),
        "high_damage_underestimation_ratio": float(
            np.mean(
                prediction[high]
                < truth[high]
            )
        ),
        "high_damage_n": int(
            np.sum(high)
        ),
    }


def calculate_damage_bins(
    seed: int,
    model_name: str,
    truth: np.ndarray,
    prediction: np.ndarray,
) -> list[dict[str, Any]]:

    bins = {
        "zero": (
            truth <= 1e-12
        ),
        "low": (
            (truth > 1e-12)
            & (truth <= 0.10)
        ),
        "medium": (
            (truth > 0.10)
            & (truth <= 0.20)
        ),
        "high": (
            truth > 0.20
        ),
    }

    rows = []

    for bin_name, mask in (
        bins.items()
    ):
        if not np.any(mask):
            raise ValueError(
                f"Seed {seed}: empty "
                f"damage bin {bin_name}."
            )

        y_true = truth[mask]
        y_pred = prediction[mask]

        error = (
            y_pred - y_true
        )

        rows.append(
            {
                "seed": seed,
                "model": model_name,
                "damage_bin": bin_name,
                "n_entries": int(
                    np.sum(mask)
                ),
                "mae": float(
                    np.mean(
                        np.abs(error)
                    )
                ),
                "rmse": float(
                    np.sqrt(
                        np.mean(
                            error ** 2
                        )
                    )
                ),
                "bias": float(
                    np.mean(error)
                ),
                "mean_true": float(
                    np.mean(
                        y_true
                    )
                ),
                "mean_prediction": float(
                    np.mean(
                        y_pred
                    )
                ),
                "underestimation_ratio": (
                    np.nan
                    if bin_name
                    == "zero"
                    else float(
                        np.mean(
                            y_pred
                            < y_true
                        )
                    )
                ),
            }
        )

    return rows


def select_ridge(
    seed: int,
    x_train: np.ndarray,
    y_train: np.ndarray,
    x_val: np.ndarray,
    y_val: np.ndarray,
) -> tuple[
    Ridge,
    dict[str, Any],
    list[dict[str, Any]],
]:

    best_model = None
    best_row = None
    candidate_rows = []

    for alpha in RIDGE_ALPHAS:

        model = Ridge(
            alpha=alpha,
            fit_intercept=True,
        )

        start = time.perf_counter()

        model.fit(
            x_train,
            y_train,
        )

        fit_seconds = float(
            time.perf_counter()
            - start
        )

        prediction = (
            clip_prediction(
                model.predict(
                    x_val
                )
            )
        )

        row = {
            "seed": seed,
            "model": "ridge",
            "candidate": (
                f"ridge_alpha_{alpha:g}"
            ),
            "alpha": float(alpha),
            "C": np.nan,
            "gamma": np.nan,
            "epsilon": np.nan,
            "val_mse": mse(
                y_val,
                prediction,
            ),
            "val_mae": mae(
                y_val,
                prediction,
            ),
            "fit_seconds": (
                fit_seconds
            ),
            "mean_support_vector_ratio": (
                np.nan
            ),
            "selected": False,
        }

        candidate_rows.append(
            row
        )

        if best_row is None:
            best_row = row.copy()
            best_model = model
        else:
            current_key = (
                row["val_mse"],
                row["candidate"],
            )

            best_key = (
                best_row[
                    "val_mse"
                ],
                best_row[
                    "candidate"
                ],
            )

            if current_key < best_key:
                best_row = row.copy()
                best_model = model

    if (
        best_model is None
        or best_row is None
    ):
        raise RuntimeError(
            "Ridge selection failed."
        )

    for row in candidate_rows:
        row["selected"] = (
            row["candidate"]
            == best_row[
                "candidate"
            ]
        )

    return (
        best_model,
        best_row,
        candidate_rows,
    )


def select_svr(
    seed: int,
    x_train: np.ndarray,
    y_train: np.ndarray,
    x_val: np.ndarray,
    y_val: np.ndarray,
    n_jobs: int,
) -> tuple[
    MultiOutputRegressor,
    dict[str, Any],
    list[dict[str, Any]],
]:

    best_model = None
    best_row = None
    candidate_rows = []

    candidate_number = 0

    total = (
        len(SVR_C_VALUES)
        * len(
            SVR_GAMMA_VALUES
        )
        * len(
            SVR_EPSILON_VALUES
        )
    )

    for C in SVR_C_VALUES:
        for gamma in (
            SVR_GAMMA_VALUES
        ):
            for epsilon in (
                SVR_EPSILON_VALUES
            ):

                candidate_number += 1

                model = (
                    MultiOutputRegressor(
                        SVR(
                            kernel="rbf",
                            C=C,
                            gamma=gamma,
                            epsilon=epsilon,
                            tol=1e-4,
                            cache_size=1024,
                        ),
                        n_jobs=n_jobs,
                    )
                )

                start = (
                    time.perf_counter()
                )

                model.fit(
                    x_train,
                    y_train,
                )

                fit_seconds = float(
                    time.perf_counter()
                    - start
                )

                prediction = (
                    clip_prediction(
                        model.predict(
                            x_val
                        )
                    )
                )

                support_counts = [
                    int(
                        len(
                            estimator.support_
                        )
                    )
                    for estimator
                    in model.estimators_
                ]

                gamma_label = (
                    f"{gamma:g}"
                    .replace(
                        ".",
                        "p",
                    )
                )

                candidate = (
                    f"rbf_svr_C_{C:g}"
                    f"_gamma_{gamma_label}"
                    f"_eps_{epsilon:g}"
                )

                row = {
                    "seed": seed,
                    "model": "rbf_svr",
                    "candidate": (
                        candidate
                    ),
                    "alpha": np.nan,
                    "C": float(C),
                    "gamma": float(
                        gamma
                    ),
                    "epsilon": float(
                        epsilon
                    ),
                    "val_mse": mse(
                        y_val,
                        prediction,
                    ),
                    "val_mae": mae(
                        y_val,
                        prediction,
                    ),
                    "fit_seconds": (
                        fit_seconds
                    ),
                    "mean_support_vector_ratio": float(
                        np.mean(
                            support_counts
                        )
                        / x_train.shape[0]
                    ),
                    "selected": False,
                }

                candidate_rows.append(
                    row
                )

                if best_row is None:
                    best_row = (
                        row.copy()
                    )
                    best_model = model
                else:
                    current_key = (
                        row["val_mse"],
                        row[
                            "candidate"
                        ],
                    )

                    best_key = (
                        best_row[
                            "val_mse"
                        ],
                        best_row[
                            "candidate"
                        ],
                    )

                    if (
                        current_key
                        < best_key
                    ):
                        best_row = (
                            row.copy()
                        )
                        best_model = (
                            model
                        )

                if (
                    candidate_number
                    % 15 == 0
                    or candidate_number
                    == total
                ):
                    print(
                        f"    SVR progress: "
                        f"{candidate_number}/"
                        f"{total}"
                    )

    if (
        best_model is None
        or best_row is None
    ):
        raise RuntimeError(
            "SVR selection failed."
        )

    for row in candidate_rows:
        row["selected"] = (
            row["candidate"]
            == best_row[
                "candidate"
            ]
        )

    return (
        best_model,
        best_row,
        candidate_rows,
    )


def confidence_interval(
    values: np.ndarray,
    confidence: float = 0.95,
) -> tuple[
    float,
    float,
]:

    values = np.asarray(
        values,
        dtype=np.float64,
    )

    n = len(values)

    mean_value = float(
        np.mean(values)
    )

    if n < 2:
        return (
            mean_value,
            mean_value,
        )

    standard_error = float(
        np.std(
            values,
            ddof=1,
        )
        / math.sqrt(n)
    )

    critical = float(
        student_t.ppf(
            (
                1.0
                + confidence
            )
            / 2.0,
            df=n - 1,
        )
    )

    margin = (
        critical
        * standard_error
    )

    return (
        mean_value - margin,
        mean_value + margin,
    )


def main() -> None:

    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--input",
        type=Path,
        default=Path(
            "data_processed/"
            "sss_fast_revision/"
            "descriptor_sets/"
            "signal_derived_with_ground/"
            "debug_plus_3000_"
            "signal_derived_with_ground_"
            "features.npz"
        ),
    )

    parser.add_argument(
        "--output-root",
        type=Path,
        default=Path(
            "results/"
            "sss_fast_revision/"
            "repeated_split_78d_ridge_svr"
        ),
    )

    parser.add_argument(
        "--n-jobs",
        type=int,
        default=4,
        help=(
            "Parallel jobs across the "
            "four storey-specific SVRs."
        ),
    )

    args = parser.parse_args()

    args.output_root.mkdir(
        parents=True,
        exist_ok=True,
    )

    prediction_root = (
        args.output_root
        / "predictions"
    )

    prediction_root.mkdir(
        parents=True,
        exist_ok=True,
    )

    split_root = (
        args.output_root
        / "splits"
    )

    split_root.mkdir(
        parents=True,
        exist_ok=True,
    )

    (
        x_full_raw,
        y_full,
        loading_metadata,
    ) = load_full_raw_dataset(
        args.input
    )

    print(
        "===== 10-SEED 78D RIDGE "
        "VS RBF-SVR ====="
    )

    print(
        "Input:",
        args.input,
    )

    print(
        "Raw reconstruction mode:",
        loading_metadata[
            "reconstruction_mode"
        ],
    )

    if (
        "mean_key"
        in loading_metadata
    ):
        print(
            "Recovered mean key:",
            loading_metadata[
                "mean_key"
            ],
        )

        print(
            "Recovered std key:",
            loading_metadata[
                "std_key"
            ],
        )

    print(
        "Full X shape:",
        x_full_raw.shape,
    )

    print(
        "Full y shape:",
        y_full.shape,
    )

    print(
        "Seeds:",
        SEEDS,
    )

    print(
        "Split:",
        N_TRAIN,
        N_VAL,
        N_TEST,
    )

    print(
        "Ridge candidates / seed:",
        len(RIDGE_ALPHAS),
    )

    print(
        "SVR candidates / seed:",
        (
            len(SVR_C_VALUES)
            * len(
                SVR_GAMMA_VALUES
            )
            * len(
                SVR_EPSILON_VALUES
            )
        ),
    )

    print(
        "SVR n_jobs:",
        args.n_jobs,
    )

    print()

    metric_rows = []
    candidate_rows = []
    damage_bin_rows = []

    for seed in SEEDS:

        print(
            "================================"
        )

        print(
            f"SEED {seed}"
        )

        print(
            "================================"
        )

        (
            train_idx,
            val_idx,
            test_idx,
        ) = make_split(
            EXPECTED_CASE_COUNT,
            seed,
        )

        np.savez_compressed(
            split_root
            / f"seed_{seed}_split.npz",
            train_idx=train_idx,
            val_idx=val_idx,
            test_idx=test_idx,
        )

        x_train_raw = (
            x_full_raw[
                train_idx
            ]
        )

        x_val_raw = (
            x_full_raw[
                val_idx
            ]
        )

        x_test_raw = (
            x_full_raw[
                test_idx
            ]
        )

        y_train = (
            y_full[
                train_idx
            ]
        )

        y_val = (
            y_full[
                val_idx
            ]
        )

        y_test = (
            y_full[
                test_idx
            ]
        )

        scaler = (
            StandardScaler()
        )

        x_train = (
            scaler.fit_transform(
                x_train_raw
            )
        )

        x_val = (
            scaler.transform(
                x_val_raw
            )
        )

        x_test = (
            scaler.transform(
                x_test_raw
            )
        )

        if not np.all(
            np.isfinite(x_train)
        ):
            raise FloatingPointError(
                f"Seed {seed}: "
                "non-finite scaled train data."
            )

        print(
            "  Selecting Ridge ..."
        )

        (
            ridge_model,
            ridge_selected,
            ridge_candidates,
        ) = select_ridge(
            seed=seed,
            x_train=x_train,
            y_train=y_train,
            x_val=x_val,
            y_val=y_val,
        )

        candidate_rows.extend(
            ridge_candidates
        )

        ridge_prediction = (
            clip_prediction(
                ridge_model.predict(
                    x_test
                )
            )
        )

        ridge_metrics = (
            calculate_metrics(
                y_test,
                ridge_prediction,
            )
        )

        metric_rows.append(
            {
                "seed": seed,
                "model": "ridge",
                "selected_candidate": (
                    ridge_selected[
                        "candidate"
                    ]
                ),
                "selected_alpha": (
                    ridge_selected[
                        "alpha"
                    ]
                ),
                "selected_C": np.nan,
                "selected_gamma": np.nan,
                "selected_epsilon": np.nan,
                "val_mse": (
                    ridge_selected[
                        "val_mse"
                    ]
                ),
                "val_mae": (
                    ridge_selected[
                        "val_mae"
                    ]
                ),
                **ridge_metrics,
            }
        )

        damage_bin_rows.extend(
            calculate_damage_bins(
                seed=seed,
                model_name="ridge",
                truth=y_test,
                prediction=(
                    ridge_prediction
                ),
            )
        )

        print(
            "  Ridge selected:",
            ridge_selected[
                "candidate"
            ],
        )

        print(
            "  Ridge test MAE:",
            f"{ridge_metrics['test_mae']:.10f}",
        )

        print(
            "  Selecting RBF-SVR ..."
        )

        (
            svr_model,
            svr_selected,
            svr_candidates,
        ) = select_svr(
            seed=seed,
            x_train=x_train,
            y_train=y_train,
            x_val=x_val,
            y_val=y_val,
            n_jobs=args.n_jobs,
        )

        candidate_rows.extend(
            svr_candidates
        )

        svr_prediction = (
            clip_prediction(
                svr_model.predict(
                    x_test
                )
            )
        )

        svr_metrics = (
            calculate_metrics(
                y_test,
                svr_prediction,
            )
        )

        metric_rows.append(
            {
                "seed": seed,
                "model": "rbf_svr",
                "selected_candidate": (
                    svr_selected[
                        "candidate"
                    ]
                ),
                "selected_alpha": np.nan,
                "selected_C": (
                    svr_selected["C"]
                ),
                "selected_gamma": (
                    svr_selected[
                        "gamma"
                    ]
                ),
                "selected_epsilon": (
                    svr_selected[
                        "epsilon"
                    ]
                ),
                "val_mse": (
                    svr_selected[
                        "val_mse"
                    ]
                ),
                "val_mae": (
                    svr_selected[
                        "val_mae"
                    ]
                ),
                **svr_metrics,
            }
        )

        damage_bin_rows.extend(
            calculate_damage_bins(
                seed=seed,
                model_name="rbf_svr",
                truth=y_test,
                prediction=(
                    svr_prediction
                ),
            )
        )

        print(
            "  SVR selected:",
            svr_selected[
                "candidate"
            ],
        )

        print(
            "  SVR test MAE:",
            f"{svr_metrics['test_mae']:.10f}",
        )

        print(
            "  Test MAE improvement:",
            (
                f"{(
                    ridge_metrics['test_mae']
                    - svr_metrics['test_mae']
                )
                / ridge_metrics['test_mae']
                * 100.0:.3f}%"
            ),
        )

        print(
            "  High-damage MAE improvement:",
            (
                f"{(
                    ridge_metrics[
                        'high_damage_mae'
                    ]
                    - svr_metrics[
                        'high_damage_mae'
                    ]
                )
                / ridge_metrics[
                    'high_damage_mae'
                ]
                * 100.0:.3f}%"
            ),
        )

        np.savez_compressed(
            prediction_root
            / f"seed_{seed}_predictions.npz",
            test_idx=test_idx,
            y_test=y_test,
            ridge_prediction=(
                ridge_prediction
            ),
            svr_prediction=(
                svr_prediction
            ),
        )

        print()

    metrics_frame = (
        pd.DataFrame(
            metric_rows
        )
        .sort_values(
            [
                "seed",
                "model",
            ]
        )
        .reset_index(
            drop=True
        )
    )

    candidates_frame = (
        pd.DataFrame(
            candidate_rows
        )
    )

    damage_frame = (
        pd.DataFrame(
            damage_bin_rows
        )
        .sort_values(
            [
                "seed",
                "model",
                "damage_bin",
            ]
        )
        .reset_index(
            drop=True
        )
    )

    # ----------------------------------
    # Aggregate model-level summaries
    # ----------------------------------

    summary_rows = []

    for model_name in [
        "ridge",
        "rbf_svr",
    ]:
        model_frame = (
            metrics_frame.loc[
                metrics_frame[
                    "model"
                ]
                == model_name
            ]
        )

        for metric in (
            PRIMARY_METRICS
        ):
            values = (
                model_frame[
                    metric
                ]
                .to_numpy(
                    dtype=np.float64
                )
            )

            ci_low, ci_high = (
                confidence_interval(
                    values
                )
            )

            summary_rows.append(
                {
                    "model": (
                        model_name
                    ),
                    "metric": metric,
                    "n_seeds": int(
                        len(values)
                    ),
                    "mean": float(
                        np.mean(values)
                    ),
                    "std": float(
                        np.std(
                            values,
                            ddof=1,
                        )
                    ),
                    "median": float(
                        np.median(
                            values
                        )
                    ),
                    "min": float(
                        np.min(values)
                    ),
                    "max": float(
                        np.max(values)
                    ),
                    "ci95_low": (
                        ci_low
                    ),
                    "ci95_high": (
                        ci_high
                    ),
                }
            )

    summary_frame = pd.DataFrame(
        summary_rows
    )

    # ----------------------------------
    # Paired seed-wise model differences
    # ----------------------------------

    paired_rows = []

    for metric in (
        PRIMARY_METRICS
    ):

        pivot = (
            metrics_frame.pivot(
                index="seed",
                columns="model",
                values=metric,
            )
            .sort_index()
        )

        ridge_values = (
            pivot["ridge"]
            .to_numpy(
                dtype=np.float64
            )
        )

        svr_values = (
            pivot["rbf_svr"]
            .to_numpy(
                dtype=np.float64
            )
        )

        difference = (
            svr_values
            - ridge_values
        )

        ci_low, ci_high = (
            confidence_interval(
                difference
            )
        )

        if np.all(
            ridge_values > 0.0
        ):
            relative_improvement = (
                (
                    ridge_values
                    - svr_values
                )
                / ridge_values
                * 100.0
            )

            mean_relative_improvement = float(
                np.mean(
                    relative_improvement
                )
            )
        else:
            mean_relative_improvement = (
                np.nan
            )

        t_result = ttest_rel(
            svr_values,
            ridge_values,
        )

        try:
            wilcoxon_result = (
                wilcoxon(
                    svr_values,
                    ridge_values,
                    alternative="two-sided",
                )
            )

            wilcoxon_statistic = float(
                wilcoxon_result.statistic
            )

            wilcoxon_p = float(
                wilcoxon_result.pvalue
            )

        except ValueError:
            wilcoxon_statistic = (
                np.nan
            )

            wilcoxon_p = (
                np.nan
            )

        paired_rows.append(
            {
                "metric": metric,
                "difference_definition": (
                    "SVR_minus_Ridge"
                ),
                "n_seeds": int(
                    len(
                        difference
                    )
                ),
                "ridge_mean": float(
                    np.mean(
                        ridge_values
                    )
                ),
                "svr_mean": float(
                    np.mean(
                        svr_values
                    )
                ),
                "mean_difference": float(
                    np.mean(
                        difference
                    )
                ),
                "std_difference": float(
                    np.std(
                        difference,
                        ddof=1,
                    )
                ),
                "ci95_difference_low": (
                    ci_low
                ),
                "ci95_difference_high": (
                    ci_high
                ),
                "svr_wins": int(
                    np.sum(
                        svr_values
                        < ridge_values
                    )
                ),
                "ridge_wins": int(
                    np.sum(
                        ridge_values
                        < svr_values
                    )
                ),
                "ties": int(
                    np.sum(
                        np.isclose(
                            svr_values,
                            ridge_values,
                        )
                    )
                ),
                "mean_relative_improvement_percent": (
                    mean_relative_improvement
                ),
                "paired_t_statistic": float(
                    t_result.statistic
                ),
                "paired_t_pvalue": float(
                    t_result.pvalue
                ),
                "wilcoxon_statistic": (
                    wilcoxon_statistic
                ),
                "wilcoxon_pvalue": (
                    wilcoxon_p
                ),
            }
        )

    paired_frame = pd.DataFrame(
        paired_rows
    )

    # ----------------------------------
    # Hyperparameter stability
    # ----------------------------------

    selected_rows = (
        metrics_frame[
            [
                "seed",
                "model",
                "selected_candidate",
                "selected_alpha",
                "selected_C",
                "selected_gamma",
                "selected_epsilon",
                "val_mse",
                "test_mae",
                "high_damage_mae",
                "high_damage_underestimation_ratio",
            ]
        ]
        .copy()
    )

    ridge_frequency = (
        selected_rows.loc[
            selected_rows[
                "model"
            ]
            == "ridge",
            "selected_alpha",
        ]
        .value_counts(
            dropna=False
        )
        .sort_index()
        .rename_axis(
            "selected_alpha"
        )
        .reset_index(
            name="count"
        )
    )

    svr_frequency = (
        selected_rows.loc[
            selected_rows[
                "model"
            ]
            == "rbf_svr"
        ]
        .groupby(
            [
                "selected_C",
                "selected_gamma",
                "selected_epsilon",
            ],
            dropna=False,
        )
        .size()
        .reset_index(
            name="count"
        )
        .sort_values(
            [
                "count",
                "selected_C",
            ],
            ascending=[
                False,
                True,
            ],
        )
        .reset_index(
            drop=True
        )
    )

    # ----------------------------------
    # Save results
    # ----------------------------------

    metrics_path = (
        args.output_root
        / "repeated_split_seed_metrics.csv"
    )

    summary_path = (
        args.output_root
        / "repeated_split_metric_summary.csv"
    )

    paired_path = (
        args.output_root
        / "repeated_split_paired_statistics.csv"
    )

    candidate_path = (
        args.output_root
        / "repeated_split_candidates.csv"
    )

    damage_path = (
        args.output_root
        / "repeated_split_damage_bins.csv"
    )

    selected_path = (
        args.output_root
        / "repeated_split_selected_hyperparameters.csv"
    )

    ridge_frequency_path = (
        args.output_root
        / "ridge_alpha_frequency.csv"
    )

    svr_frequency_path = (
        args.output_root
        / "svr_hyperparameter_frequency.csv"
    )

    report_path = (
        args.output_root
        / "repeated_split_report.json"
    )

    metrics_frame.to_csv(
        metrics_path,
        index=False,
    )

    summary_frame.to_csv(
        summary_path,
        index=False,
    )

    paired_frame.to_csv(
        paired_path,
        index=False,
    )

    candidates_frame.to_csv(
        candidate_path,
        index=False,
    )

    damage_frame.to_csv(
        damage_path,
        index=False,
    )

    selected_rows.to_csv(
        selected_path,
        index=False,
    )

    ridge_frequency.to_csv(
        ridge_frequency_path,
        index=False,
    )

    svr_frequency.to_csv(
        svr_frequency_path,
        index=False,
    )

    report = {
        "experiment": (
            "10_seed_78D_Ridge_vs_RBF_SVR"
        ),
        "descriptor_set": (
            "signal_derived_with_ground"
        ),
        "feature_count": (
            EXPECTED_FEATURE_COUNT
        ),
        "case_count": (
            EXPECTED_CASE_COUNT
        ),
        "seeds": SEEDS,
        "split_sizes": {
            "train": N_TRAIN,
            "validation": N_VAL,
            "test": N_TEST,
        },
        "preprocessing": (
            "StandardScaler fitted separately "
            "on each seed's training fold only."
        ),
        "selection_criterion": (
            "clipped validation MSE"
        ),
        "prediction_clip": [
            0.0,
            0.5,
        ],
        "ridge_candidate_count": (
            len(RIDGE_ALPHAS)
        ),
        "svr_candidate_count": (
            len(SVR_C_VALUES)
            * len(
                SVR_GAMMA_VALUES
            )
            * len(
                SVR_EPSILON_VALUES
            )
        ),
        "raw_dataset_loading": (
            loading_metadata
        ),
        "statistical_note": (
            "Paired tests are descriptive robustness "
            "evidence across ten repeated holdout splits; "
            "they should not be interpreted as proving "
            "population-level superiority in isolation."
        ),
        "output_files": {
            "seed_metrics": str(
                metrics_path
            ),
            "summary": str(
                summary_path
            ),
            "paired_statistics": str(
                paired_path
            ),
            "candidates": str(
                candidate_path
            ),
            "damage_bins": str(
                damage_path
            ),
            "selected_hyperparameters": str(
                selected_path
            ),
            "ridge_frequency": str(
                ridge_frequency_path
            ),
            "svr_frequency": str(
                svr_frequency_path
            ),
        },
    }

    with report_path.open(
        "w",
        encoding="utf-8",
    ) as file:
        json.dump(
            report,
            file,
            indent=2,
            ensure_ascii=False,
        )

    # ----------------------------------
    # Console summary
    # ----------------------------------

    print()
    print(
        "===== SEED-BY-SEED RESULTS ====="
    )

    seed_display = (
        metrics_frame.pivot(
            index="seed",
            columns="model",
            values=[
                "test_mae",
                "high_damage_mae",
                "high_damage_underestimation_ratio",
            ],
        )
    )

    print(
        seed_display.to_string(
            float_format=lambda x: (
                f"{x:.10f}"
            )
        )
    )

    print()
    print(
        "===== AGGREGATE METRICS ====="
    )

    print(
        summary_frame.loc[
            summary_frame[
                "metric"
            ].isin(
                [
                    "test_mae",
                    "test_rmse",
                    "damaged_entry_mae",
                    "high_damage_mae",
                    "high_damage_abs_bias",
                    "high_damage_underestimation_ratio",
                ]
            )
        ][
            [
                "model",
                "metric",
                "mean",
                "std",
                "ci95_low",
                "ci95_high",
            ]
        ].to_string(
            index=False,
            float_format=lambda x: (
                f"{x:.10f}"
            ),
        )
    )

    print()
    print(
        "===== PAIRED MODEL COMPARISON ====="
    )

    print(
        paired_frame[
            [
                "metric",
                "ridge_mean",
                "svr_mean",
                "mean_difference",
                "ci95_difference_low",
                "ci95_difference_high",
                "svr_wins",
                "ridge_wins",
                "mean_relative_improvement_percent",
                "paired_t_pvalue",
                "wilcoxon_pvalue",
            ]
        ].to_string(
            index=False,
            float_format=lambda x: (
                f"{x:.10f}"
            ),
        )
    )

    print()
    print(
        "===== SELECTED HYPERPARAMETERS ====="
    )

    print(
        selected_rows.to_string(
            index=False,
            float_format=lambda x: (
                f"{x:.10f}"
            ),
        )
    )

    print()
    print(
        "===== RIDGE ALPHA FREQUENCY ====="
    )

    print(
        ridge_frequency.to_string(
            index=False,
        )
    )

    print()
    print(
        "===== SVR HYPERPARAMETER FREQUENCY ====="
    )

    print(
        svr_frequency.to_string(
            index=False,
        )
    )

    print()
    print(
        "===== INTEGRITY CHECKS ====="
    )

    print(
        "Case count:",
        x_full_raw.shape[0],
    )

    print(
        "Feature count:",
        x_full_raw.shape[1],
    )

    print(
        "Seeds completed:",
        (
            metrics_frame[
                "seed"
            ]
            .nunique()
        ),
    )

    print(
        "Models per seed:",
        (
            metrics_frame.groupby(
                "seed"
            )["model"]
            .nunique()
            .min()
        ),
    )

    print(
        "Per-seed scaling:",
        True,
    )

    print(
        "Paired splits:",
        True,
    )

    print()
    print(
        "CHECK PASSED: 10-seed "
        "repeated-split comparison completed."
    )

    print(
        "Metrics:",
        metrics_path,
    )

    print(
        "Summary:",
        summary_path,
    )

    print(
        "Paired statistics:",
        paired_path,
    )

    print(
        "Report:",
        report_path,
    )


if __name__ == "__main__":
    main()
