"""
10-seed paired information-availability comparison:

78D signal-derived-with-ground RBF-SVR
vs
92D oracle_full / privileged-information RBF-SVR

Design
------
- Reuse EXACTLY the ten split files generated by the previous
  78D Ridge-vs-SVR repeated-split experiment.
- Reuse the already-frozen 78D seed-level SVR results.
- Train only the 92D representation in this script.
- Per-seed StandardScaler is fitted on that seed's 92D training fold only.
- Same frozen 75-candidate RBF-SVR grid as the 78D experiment.
- Hyperparameters selected using clipped validation MSE only.
- Test evaluated only after validation selection.

Scientific question
-------------------
Does privileged simulation information provide a stable performance
advantage over the 78D deployable/signal-derived representation
when estimator flexibility is held constant?
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
import time
from typing import Any

import numpy as np
import pandas as pd
from scipy.stats import t as student_t
from scipy.stats import ttest_rel, wilcoxon
from sklearn.multioutput import MultiOutputRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVR


SEEDS = list(range(10))

EXPECTED_CASE_COUNT = 3000
EXPECTED_78D_FEATURE_COUNT = 78
EXPECTED_92D_FEATURE_COUNT = 92

N_TRAIN = 2100
N_VAL = 450
N_TEST = 450


SVR_C_VALUES = [
    100.0,
    300.0,
    500.0,
    750.0,
    1000.0,
]

SVR_GAMMA_VALUES = [
    0.0005,
    0.00075,
    0.001,
    0.003,
    0.01,
]

SVR_EPSILON_VALUES = [
    0.02,
    0.03,
    0.04,
]


PRIMARY_METRICS = [
    "test_mae",
    "test_rmse",
    "damaged_entry_mae",
    "zero_damage_mae",
    "high_damage_mae",
    "high_damage_abs_bias",
    "high_damage_underestimation_ratio",
]


def recover_raw_features(
    path: Path,
    expected_features: int,
) -> tuple[
    np.ndarray,
    np.ndarray,
    dict[str, Any],
]:
    """
    Recover complete raw descriptor matrix in original canonical order.

    Preferred:
        F_train_raw / F_val_raw / F_test_raw

    Fallback:
        inverse standardisation using stored mean/std.

    Never random-split already-standardised canonical F_* directly.
    """
    if not path.is_file():
        raise FileNotFoundError(path)

    required = {
        "F_train",
        "F_val",
        "F_test",
        "y_train",
        "y_val",
        "y_test",
    }

    with np.load(
        path,
        allow_pickle=False,
    ) as data:

        missing = sorted(
            required
            - set(data.files)
        )

        if missing:
            raise KeyError(
                f"{path} missing arrays: {missing}"
            )

        F_train = np.asarray(
            data["F_train"],
            dtype=np.float64,
        )

        F_val = np.asarray(
            data["F_val"],
            dtype=np.float64,
        )

        F_test = np.asarray(
            data["F_test"],
            dtype=np.float64,
        )

        y_train = np.asarray(
            data["y_train"],
            dtype=np.float64,
        )

        y_val = np.asarray(
            data["y_val"],
            dtype=np.float64,
        )

        y_test = np.asarray(
            data["y_test"],
            dtype=np.float64,
        )

        raw_keys = {
            "F_train_raw",
            "F_val_raw",
            "F_test_raw",
        }

        metadata: dict[str, Any] = {}

        if raw_keys.issubset(
            set(data.files)
        ):
            raw_train = np.asarray(
                data["F_train_raw"],
                dtype=np.float64,
            )

            raw_val = np.asarray(
                data["F_val_raw"],
                dtype=np.float64,
            )

            raw_test = np.asarray(
                data["F_test_raw"],
                dtype=np.float64,
            )

            metadata[
                "reconstruction_mode"
            ] = "explicit_raw_arrays"

        else:
            mean_candidates = [
                "feature_mean",
                "feature_means",
                "F_mean",
                "train_feature_mean",
                "mean",
            ]

            std_candidates = [
                "feature_std",
                "feature_stds",
                "F_std",
                "train_feature_std",
                "std",
            ]

            feature_mean = None
            mean_key = None

            for key in mean_candidates:
                if key in data.files:
                    candidate = np.asarray(
                        data[key]
                    )

                    if (
                        candidate.ndim == 1
                        and candidate.shape[0]
                        == expected_features
                        and np.issubdtype(
                            candidate.dtype,
                            np.number,
                        )
                    ):
                        feature_mean = np.asarray(
                            candidate,
                            dtype=np.float64,
                        )

                        mean_key = key
                        break

            feature_std = None
            std_key = None

            for key in std_candidates:
                if key in data.files:
                    candidate = np.asarray(
                        data[key]
                    )

                    if (
                        candidate.ndim == 1
                        and candidate.shape[0]
                        == expected_features
                        and np.issubdtype(
                            candidate.dtype,
                            np.number,
                        )
                    ):
                        feature_std = np.asarray(
                            candidate,
                            dtype=np.float64,
                        )

                        std_key = key
                        break

            if (
                feature_mean is None
                or feature_std is None
            ):
                # Flexible fallback: look for one numeric vector
                # containing "mean"/"std" in its array name.
                possible_means = []
                possible_stds = []

                for key in data.files:
                    try:
                        candidate = np.asarray(
                            data[key]
                        )
                    except Exception:
                        continue

                    if not (
                        candidate.ndim == 1
                        and candidate.shape[0]
                        == expected_features
                        and np.issubdtype(
                            candidate.dtype,
                            np.number,
                        )
                    ):
                        continue

                    if "mean" in key.lower():
                        possible_means.append(
                            (
                                key,
                                candidate,
                            )
                        )

                    if "std" in key.lower():
                        possible_stds.append(
                            (
                                key,
                                candidate,
                            )
                        )

                if (
                    feature_mean is None
                    and len(
                        possible_means
                    ) == 1
                ):
                    mean_key = (
                        possible_means[
                            0
                        ][0]
                    )

                    feature_mean = np.asarray(
                        possible_means[
                            0
                        ][1],
                        dtype=np.float64,
                    )

                if (
                    feature_std is None
                    and len(
                        possible_stds
                    ) == 1
                ):
                    std_key = (
                        possible_stds[
                            0
                        ][0]
                    )

                    feature_std = np.asarray(
                        possible_stds[
                            0
                        ][1],
                        dtype=np.float64,
                    )

            if (
                feature_mean is None
                or feature_std is None
            ):
                raise RuntimeError(
                    "Cannot recover raw features from "
                    f"{path}. Available keys: "
                    f"{sorted(data.files)}"
                )

            raw_train = (
                F_train
                * feature_std
                + feature_mean
            )

            raw_val = (
                F_val
                * feature_std
                + feature_mean
            )

            raw_test = (
                F_test
                * feature_std
                + feature_mean
            )

            metadata[
                "reconstruction_mode"
            ] = "inverse_standardisation"

            metadata[
                "mean_key"
            ] = mean_key

            metadata[
                "std_key"
            ] = std_key

        optional_identity = {}

        for key in [
            "case_id_train",
            "case_id_val",
            "case_id_test",
            "train_idx",
            "val_idx",
            "test_idx",
        ]:
            if key in data.files:
                optional_identity[
                    key
                ] = np.asarray(
                    data[key]
                )

    x_full = np.vstack(
        [
            raw_train,
            raw_val,
            raw_test,
        ]
    )

    y_full = np.vstack(
        [
            y_train,
            y_val,
            y_test,
        ]
    )

    if (
        x_full.shape
        != (
            EXPECTED_CASE_COUNT,
            expected_features,
        )
    ):
        raise ValueError(
            f"{path}: unexpected X shape "
            f"{x_full.shape}"
        )

    if (
        y_full.shape
        != (
            EXPECTED_CASE_COUNT,
            4,
        )
    ):
        raise ValueError(
            f"{path}: unexpected y shape "
            f"{y_full.shape}"
        )

    if not np.all(
        np.isfinite(
            x_full
        )
    ):
        raise FloatingPointError(
            f"{path}: non-finite raw features."
        )

    if not np.all(
        np.isfinite(
            y_full
        )
    ):
        raise FloatingPointError(
            f"{path}: non-finite targets."
        )

    metadata[
        "optional_identity"
    ] = optional_identity

    return (
        x_full,
        y_full,
        metadata,
    )


def verify_canonical_alignment(
    y_78: np.ndarray,
    y_92: np.ndarray,
    metadata_78: dict[str, Any],
    metadata_92: dict[str, Any],
) -> None:
    """Confirm that canonical concatenation order is identical."""

    if not np.array_equal(
        y_78,
        y_92,
    ):
        raise RuntimeError(
            "STOP: 78D and 92D canonical target "
            "ordering differs."
        )

    identity_78 = metadata_78[
        "optional_identity"
    ]

    identity_92 = metadata_92[
        "optional_identity"
    ]

    for key in sorted(
        set(identity_78)
        & set(identity_92)
    ):
        if not np.array_equal(
            identity_78[key],
            identity_92[key],
        ):
            raise RuntimeError(
                "STOP: 78D and 92D canonical "
                f"identifier differs: {key}"
            )


def load_split(
    split_root: Path,
    seed: int,
) -> tuple[
    np.ndarray,
    np.ndarray,
    np.ndarray,
]:

    path = (
        split_root
        / f"seed_{seed}_split.npz"
    )

    if not path.is_file():
        raise FileNotFoundError(
            path
        )

    with np.load(
        path,
        allow_pickle=False,
    ) as data:
        train_idx = np.asarray(
            data["train_idx"],
            dtype=np.int64,
        )

        val_idx = np.asarray(
            data["val_idx"],
            dtype=np.int64,
        )

        test_idx = np.asarray(
            data["test_idx"],
            dtype=np.int64,
        )

    if (
        len(train_idx)
        != N_TRAIN
        or len(val_idx)
        != N_VAL
        or len(test_idx)
        != N_TEST
    ):
        raise RuntimeError(
            f"Seed {seed}: split-size mismatch."
        )

    combined = np.concatenate(
        [
            train_idx,
            val_idx,
            test_idx,
        ]
    )

    if (
        len(
            np.unique(
                combined
            )
        )
        != EXPECTED_CASE_COUNT
    ):
        raise RuntimeError(
            f"Seed {seed}: overlap or omission "
            "in split indices."
        )

    if (
        np.min(combined) < 0
        or np.max(combined)
        >= EXPECTED_CASE_COUNT
    ):
        raise RuntimeError(
            f"Seed {seed}: out-of-range index."
        )

    return (
        train_idx,
        val_idx,
        test_idx,
    )


def clip_prediction(
    prediction: np.ndarray,
) -> np.ndarray:

    return np.clip(
        np.asarray(
            prediction,
            dtype=np.float64,
        ),
        0.0,
        0.5,
    )


def mse(
    truth: np.ndarray,
    prediction: np.ndarray,
) -> float:

    error = (
        np.asarray(
            prediction
        )
        - np.asarray(
            truth
        )
    )

    return float(
        np.mean(
            error ** 2
        )
    )


def mae(
    truth: np.ndarray,
    prediction: np.ndarray,
) -> float:

    return float(
        np.mean(
            np.abs(
                np.asarray(
                    prediction
                )
                - np.asarray(
                    truth
                )
            )
        )
    )


def calculate_metrics(
    truth: np.ndarray,
    prediction: np.ndarray,
) -> dict[str, float]:

    truth = np.asarray(
        truth,
        dtype=np.float64,
    )

    prediction = np.asarray(
        prediction,
        dtype=np.float64,
    )

    error = (
        prediction
        - truth
    )

    damaged = (
        truth > 1e-12
    )

    zero = (
        truth <= 1e-12
    )

    high = (
        truth > 0.20
    )

    high_bias = float(
        np.mean(
            error[
                high
            ]
        )
    )

    return {
        "test_mae": float(
            np.mean(
                np.abs(
                    error
                )
            )
        ),
        "test_rmse": float(
            np.sqrt(
                np.mean(
                    error ** 2
                )
            )
        ),
        "test_bias": float(
            np.mean(
                error
            )
        ),
        "damaged_entry_mae": float(
            np.mean(
                np.abs(
                    error[
                        damaged
                    ]
                )
            )
        ),
        "zero_damage_mae": float(
            np.mean(
                np.abs(
                    error[
                        zero
                    ]
                )
            )
        ),
        "high_damage_mae": float(
            np.mean(
                np.abs(
                    error[
                        high
                    ]
                )
            )
        ),
        "high_damage_bias": (
            high_bias
        ),
        "high_damage_abs_bias": (
            abs(
                high_bias
            )
        ),
        "high_damage_underestimation_ratio": float(
            np.mean(
                prediction[
                    high
                ]
                < truth[
                    high
                ]
            )
        ),
        "high_damage_n": int(
            np.sum(
                high
            )
        ),
    }


def damage_bins(
    seed: int,
    truth: np.ndarray,
    prediction: np.ndarray,
) -> list[
    dict[str, Any]
]:

    bins = {
        "zero": (
            truth <= 1e-12
        ),
        "low": (
            (truth > 1e-12)
            & (truth <= 0.10)
        ),
        "medium": (
            (truth > 0.10)
            & (truth <= 0.20)
        ),
        "high": (
            truth > 0.20
        ),
    }

    rows = []

    for name, mask in (
        bins.items()
    ):
        if not np.any(
            mask
        ):
            raise RuntimeError(
                f"Seed {seed}: empty damage bin {name}."
            )

        y_true = truth[
            mask
        ]

        y_pred = prediction[
            mask
        ]

        error = (
            y_pred
            - y_true
        )

        rows.append(
            {
                "seed": seed,
                "descriptor_set": (
                    "oracle_full"
                ),
                "model": (
                    "rbf_svr"
                ),
                "damage_bin": name,
                "n_entries": int(
                    np.sum(
                        mask
                    )
                ),
                "mae": float(
                    np.mean(
                        np.abs(
                            error
                        )
                    )
                ),
                "rmse": float(
                    np.sqrt(
                        np.mean(
                            error ** 2
                        )
                    )
                ),
                "bias": float(
                    np.mean(
                        error
                    )
                ),
                "mean_true": float(
                    np.mean(
                        y_true
                    )
                ),
                "mean_prediction": float(
                    np.mean(
                        y_pred
                    )
                ),
                "underestimation_ratio": (
                    np.nan
                    if name
                    == "zero"
                    else float(
                        np.mean(
                            y_pred
                            < y_true
                        )
                    )
                ),
            }
        )

    return rows


def select_svr(
    seed: int,
    x_train: np.ndarray,
    y_train: np.ndarray,
    x_val: np.ndarray,
    y_val: np.ndarray,
    n_jobs: int,
) -> tuple[
    MultiOutputRegressor,
    dict[str, Any],
    list[
        dict[str, Any]
    ],
]:

    best_model = None
    best_row = None

    candidate_rows = []

    total = (
        len(
            SVR_C_VALUES
        )
        * len(
            SVR_GAMMA_VALUES
        )
        * len(
            SVR_EPSILON_VALUES
        )
    )

    counter = 0

    for C in SVR_C_VALUES:
        for gamma in (
            SVR_GAMMA_VALUES
        ):
            for epsilon in (
                SVR_EPSILON_VALUES
            ):
                counter += 1

                estimator = (
                    MultiOutputRegressor(
                        SVR(
                            kernel="rbf",
                            C=C,
                            gamma=gamma,
                            epsilon=epsilon,
                            tol=1e-4,
                            cache_size=1024,
                        ),
                        n_jobs=n_jobs,
                    )
                )

                start = (
                    time.perf_counter()
                )

                estimator.fit(
                    x_train,
                    y_train,
                )

                fit_seconds = float(
                    time.perf_counter()
                    - start
                )

                val_prediction = (
                    clip_prediction(
                        estimator.predict(
                            x_val
                        )
                    )
                )

                support_counts = [
                    int(
                        len(
                            model.support_
                        )
                    )
                    for model
                    in estimator.estimators_
                ]

                gamma_label = (
                    f"{gamma:g}"
                    .replace(
                        ".",
                        "p",
                    )
                )

                candidate = (
                    f"rbf_svr_C_{C:g}"
                    f"_gamma_{gamma_label}"
                    f"_eps_{epsilon:g}"
                )

                row = {
                    "seed": seed,
                    "descriptor_set": (
                        "oracle_full"
                    ),
                    "candidate": (
                        candidate
                    ),
                    "C": float(
                        C
                    ),
                    "gamma": float(
                        gamma
                    ),
                    "epsilon": float(
                        epsilon
                    ),
                    "val_mse": mse(
                        y_val,
                        val_prediction,
                    ),
                    "val_mae": mae(
                        y_val,
                        val_prediction,
                    ),
                    "fit_seconds": (
                        fit_seconds
                    ),
                    "mean_support_vector_ratio": float(
                        np.mean(
                            support_counts
                        )
                        / x_train.shape[0]
                    ),
                    "selected": False,
                }

                candidate_rows.append(
                    row
                )

                if (
                    best_row is None
                ):
                    best_row = (
                        row.copy()
                    )

                    best_model = (
                        estimator
                    )

                else:
                    current_key = (
                        row[
                            "val_mse"
                        ],
                        row[
                            "candidate"
                        ],
                    )

                    best_key = (
                        best_row[
                            "val_mse"
                        ],
                        best_row[
                            "candidate"
                        ],
                    )

                    if (
                        current_key
                        < best_key
                    ):
                        best_row = (
                            row.copy()
                        )

                        best_model = (
                            estimator
                        )

                if (
                    counter % 15
                    == 0
                    or counter
                    == total
                ):
                    print(
                        f"    92D SVR progress: "
                        f"{counter}/{total}"
                    )

    if (
        best_model is None
        or best_row is None
    ):
        raise RuntimeError(
            f"Seed {seed}: SVR selection failed."
        )

    for row in (
        candidate_rows
    ):
        row[
            "selected"
        ] = (
            row[
                "candidate"
            ]
            == best_row[
                "candidate"
            ]
        )

    return (
        best_model,
        best_row,
        candidate_rows,
    )


def confidence_interval(
    values: np.ndarray,
) -> tuple[
    float,
    float,
]:

    values = np.asarray(
        values,
        dtype=np.float64,
    )

    mean_value = float(
        np.mean(
            values
        )
    )

    if len(
        values
    ) < 2:
        return (
            mean_value,
            mean_value,
        )

    standard_error = float(
        np.std(
            values,
            ddof=1,
        )
        / math.sqrt(
            len(
                values
            )
        )
    )

    critical = float(
        student_t.ppf(
            0.975,
            df=(
                len(
                    values
                )
                - 1
            ),
        )
    )

    margin = (
        critical
        * standard_error
    )

    return (
        mean_value
        - margin,
        mean_value
        + margin,
    )


def main() -> None:

    parser = (
        argparse.ArgumentParser()
    )

    parser.add_argument(
        "--input-78d",
        type=Path,
        default=Path(
            "data_processed/"
            "sss_fast_revision/"
            "descriptor_sets/"
            "signal_derived_with_ground/"
            "debug_plus_3000_"
            "signal_derived_with_ground_"
            "features.npz"
        ),
    )

    parser.add_argument(
        "--input-92d",
        type=Path,
        default=Path(
            "data_processed/"
            "sss_fast_revision/"
            "descriptor_sets/"
            "oracle_full/"
            "debug_plus_3000_"
            "oracle_full_features.npz"
        ),
    )

    parser.add_argument(
        "--split-root",
        type=Path,
        default=Path(
            "results/"
            "sss_fast_revision/"
            "repeated_split_78d_ridge_svr/"
            "splits"
        ),
    )

    parser.add_argument(
        "--reference-78d-metrics",
        type=Path,
        default=Path(
            "results/"
            "sss_fast_revision/"
            "repeated_split_78d_ridge_svr/"
            "repeated_split_seed_metrics.csv"
        ),
    )

    parser.add_argument(
        "--output-root",
        type=Path,
        default=Path(
            "results/"
            "sss_fast_revision/"
            "repeated_split_78d_92d_svr"
        ),
    )

    parser.add_argument(
        "--n-jobs",
        type=int,
        default=4,
    )

    args = (
        parser.parse_args()
    )

    args.output_root.mkdir(
        parents=True,
        exist_ok=True,
    )

    prediction_root = (
        args.output_root
        / "predictions"
    )

    prediction_root.mkdir(
        parents=True,
        exist_ok=True,
    )

    (
        x_78_raw,
        y_78,
        metadata_78,
    ) = recover_raw_features(
        args.input_78d,
        EXPECTED_78D_FEATURE_COUNT,
    )

    (
        x_92_raw,
        y_92,
        metadata_92,
    ) = recover_raw_features(
        args.input_92d,
        EXPECTED_92D_FEATURE_COUNT,
    )

    verify_canonical_alignment(
        y_78=y_78,
        y_92=y_92,
        metadata_78=metadata_78,
        metadata_92=metadata_92,
    )

    if not (
        args.reference_78d_metrics
        .is_file()
    ):
        raise FileNotFoundError(
            args.reference_78d_metrics
        )

    reference_frame = (
        pd.read_csv(
            args.reference_78d_metrics
        )
    )

    reference_78 = (
        reference_frame.loc[
            reference_frame[
                "model"
            ]
            == "rbf_svr"
        ]
        .copy()
        .sort_values(
            "seed"
        )
        .reset_index(
            drop=True
        )
    )

    if (
        reference_78.shape[0]
        != len(
            SEEDS
        )
    ):
        raise RuntimeError(
            "Expected exactly ten frozen "
            "78D SVR seed rows."
        )

    if (
        reference_78[
            "seed"
        ]
        .tolist()
        != SEEDS
    ):
        raise RuntimeError(
            "Frozen 78D SVR results do not "
            "contain seeds 0..9 exactly."
        )

    print(
        "===== 10-SEED 78D VS 92D "
        "RBF-SVR INFORMATION COMPARISON ====="
    )

    print(
        "78D reconstruction:",
        metadata_78[
            "reconstruction_mode"
        ],
    )

    print(
        "92D reconstruction:",
        metadata_92[
            "reconstruction_mode"
        ],
    )

    print(
        "Canonical target alignment: PASSED"
    )

    print(
        "Frozen 78D seed results loaded:",
        len(
            reference_78
        ),
    )

    print(
        "Reusing split files from:",
        args.split_root,
    )

    print(
        "92D candidates / seed:",
        (
            len(
                SVR_C_VALUES
            )
            * len(
                SVR_GAMMA_VALUES
            )
            * len(
                SVR_EPSILON_VALUES
            )
        ),
    )

    print()

    rows_92 = []
    candidate_rows = []
    damage_rows = []

    for seed in SEEDS:

        print(
            "================================"
        )

        print(
            f"SEED {seed}"
        )

        print(
            "================================"
        )

        (
            train_idx,
            val_idx,
            test_idx,
        ) = load_split(
            args.split_root,
            seed,
        )

        x_train_raw = (
            x_92_raw[
                train_idx
            ]
        )

        x_val_raw = (
            x_92_raw[
                val_idx
            ]
        )

        x_test_raw = (
            x_92_raw[
                test_idx
            ]
        )

        y_train = (
            y_92[
                train_idx
            ]
        )

        y_val = (
            y_92[
                val_idx
            ]
        )

        y_test = (
            y_92[
                test_idx
            ]
        )

        scaler = (
            StandardScaler()
        )

        x_train = (
            scaler.fit_transform(
                x_train_raw
            )
        )

        x_val = (
            scaler.transform(
                x_val_raw
            )
        )

        x_test = (
            scaler.transform(
                x_test_raw
            )
        )

        (
            model,
            selected,
            candidates,
        ) = select_svr(
            seed=seed,
            x_train=x_train,
            y_train=y_train,
            x_val=x_val,
            y_val=y_val,
            n_jobs=args.n_jobs,
        )

        candidate_rows.extend(
            candidates
        )

        test_prediction = (
            clip_prediction(
                model.predict(
                    x_test
                )
            )
        )

        metrics = (
            calculate_metrics(
                y_test,
                test_prediction,
            )
        )

        row = {
            "seed": seed,
            "descriptor_set": (
                "oracle_full"
            ),
            "n_features": 92,
            "model": "rbf_svr",
            "selected_candidate": (
                selected[
                    "candidate"
                ]
            ),
            "selected_C": (
                selected[
                    "C"
                ]
            ),
            "selected_gamma": (
                selected[
                    "gamma"
                ]
            ),
            "selected_epsilon": (
                selected[
                    "epsilon"
                ]
            ),
            "val_mse": (
                selected[
                    "val_mse"
                ]
            ),
            "val_mae": (
                selected[
                    "val_mae"
                ]
            ),
            "mean_support_vector_ratio": (
                selected[
                    "mean_support_vector_ratio"
                ]
            ),
            **metrics,
        }

        rows_92.append(
            row
        )

        damage_rows.extend(
            damage_bins(
                seed=seed,
                truth=y_test,
                prediction=(
                    test_prediction
                ),
            )
        )

        np.savez_compressed(
            prediction_root
            / f"seed_{seed}_92d_predictions.npz",
            seed=np.asarray(
                seed
            ),
            test_idx=test_idx,
            y_test=y_test,
            prediction=(
                test_prediction
            ),
        )

        reference_row = (
            reference_78.loc[
                reference_78[
                    "seed"
                ]
                == seed
            ]
            .iloc[0]
        )

        improvement = (
            (
                float(
                    reference_row[
                        "test_mae"
                    ]
                )
                - metrics[
                    "test_mae"
                ]
            )
            / float(
                reference_row[
                    "test_mae"
                ]
            )
            * 100.0
        )

        print(
            "  92D selected:",
            selected[
                "candidate"
            ],
        )

        print(
            "  78D frozen test MAE:",
            f"{float(reference_row['test_mae']):.10f}",
        )

        print(
            "  92D test MAE:",
            f"{metrics['test_mae']:.10f}",
        )

        print(
            "  92D relative MAE improvement:",
            f"{improvement:.3f}%",
        )

        print(
            "  78D high-damage MAE:",
            f"{float(reference_row['high_damage_mae']):.10f}",
        )

        print(
            "  92D high-damage MAE:",
            f"{metrics['high_damage_mae']:.10f}",
        )

        print()

    frame_92 = (
        pd.DataFrame(
            rows_92
        )
        .sort_values(
            "seed"
        )
        .reset_index(
            drop=True
        )
    )

    candidates_frame = (
        pd.DataFrame(
            candidate_rows
        )
    )

    damage_frame = (
        pd.DataFrame(
            damage_rows
        )
    )

    # Create common paired table.
    paired_seed_rows = []

    for seed in SEEDS:

        row78 = (
            reference_78.loc[
                reference_78[
                    "seed"
                ]
                == seed
            ]
            .iloc[0]
        )

        row92 = (
            frame_92.loc[
                frame_92[
                    "seed"
                ]
                == seed
            ]
            .iloc[0]
        )

        output = {
            "seed": seed,
        }

        for metric in (
            PRIMARY_METRICS
        ):
            value78 = float(
                row78[
                    metric
                ]
            )

            value92 = float(
                row92[
                    metric
                ]
            )

            output[
                f"78d_{metric}"
            ] = value78

            output[
                f"92d_{metric}"
            ] = value92

            output[
                f"difference_92d_minus_78d_{metric}"
            ] = (
                value92
                - value78
            )

            if value78 > 0.0:
                output[
                    f"relative_improvement_percent_{metric}"
                ] = (
                    (
                        value78
                        - value92
                    )
                    / value78
                    * 100.0
                )

        paired_seed_rows.append(
            output
        )

    paired_seed_frame = (
        pd.DataFrame(
            paired_seed_rows
        )
    )

    # Aggregate metric statistics.
    summary_rows = []
    paired_stat_rows = []

    for metric in (
        PRIMARY_METRICS
    ):

        values78 = (
            reference_78[
                metric
            ]
            .to_numpy(
                dtype=np.float64
            )
        )

        values92 = (
            frame_92[
                metric
            ]
            .to_numpy(
                dtype=np.float64
            )
        )

        for (
            descriptor_name,
            values,
        ) in [
            (
                "78D_signal_derived_with_ground",
                values78,
            ),
            (
                "92D_oracle_full",
                values92,
            ),
        ]:
            (
                ci_low,
                ci_high,
            ) = confidence_interval(
                values
            )

            summary_rows.append(
                {
                    "descriptor_set": (
                        descriptor_name
                    ),
                    "metric": metric,
                    "n_seeds": len(
                        values
                    ),
                    "mean": float(
                        np.mean(
                            values
                        )
                    ),
                    "std": float(
                        np.std(
                            values,
                            ddof=1,
                        )
                    ),
                    "median": float(
                        np.median(
                            values
                        )
                    ),
                    "min": float(
                        np.min(
                            values
                        )
                    ),
                    "max": float(
                        np.max(
                            values
                        )
                    ),
                    "ci95_low": (
                        ci_low
                    ),
                    "ci95_high": (
                        ci_high
                    ),
                }
            )

        difference = (
            values92
            - values78
        )

        (
            difference_low,
            difference_high,
        ) = confidence_interval(
            difference
        )

        relative_improvement = (
            (
                values78
                - values92
            )
            / values78
            * 100.0
        )

        t_result = (
            ttest_rel(
                values92,
                values78,
            )
        )

        try:
            w_result = (
                wilcoxon(
                    values92,
                    values78,
                    alternative="two-sided",
                )
            )

            w_stat = float(
                w_result.statistic
            )

            w_p = float(
                w_result.pvalue
            )

        except ValueError:
            w_stat = np.nan
            w_p = np.nan

        paired_stat_rows.append(
            {
                "metric": metric,
                "difference_definition": (
                    "92D_minus_78D"
                ),
                "n_seeds": len(
                    difference
                ),
                "78d_mean": float(
                    np.mean(
                        values78
                    )
                ),
                "92d_mean": float(
                    np.mean(
                        values92
                    )
                ),
                "mean_difference": float(
                    np.mean(
                        difference
                    )
                ),
                "std_difference": float(
                    np.std(
                        difference,
                        ddof=1,
                    )
                ),
                "ci95_difference_low": (
                    difference_low
                ),
                "ci95_difference_high": (
                    difference_high
                ),
                "92d_wins": int(
                    np.sum(
                        values92
                        < values78
                    )
                ),
                "78d_wins": int(
                    np.sum(
                        values78
                        < values92
                    )
                ),
                "ties": int(
                    np.sum(
                        np.isclose(
                            values92,
                            values78,
                        )
                    )
                ),
                "mean_relative_improvement_percent": float(
                    np.mean(
                        relative_improvement
                    )
                ),
                "paired_t_statistic": float(
                    t_result.statistic
                ),
                "paired_t_pvalue": float(
                    t_result.pvalue
                ),
                "wilcoxon_statistic": (
                    w_stat
                ),
                "wilcoxon_pvalue": (
                    w_p
                ),
            }
        )

    summary_frame = (
        pd.DataFrame(
            summary_rows
        )
    )

    paired_stats_frame = (
        pd.DataFrame(
            paired_stat_rows
        )
    )

    selected_92 = (
        frame_92[
            [
                "seed",
                "selected_candidate",
                "selected_C",
                "selected_gamma",
                "selected_epsilon",
                "val_mse",
                "val_mae",
                "mean_support_vector_ratio",
                "test_mae",
                "high_damage_mae",
                "high_damage_underestimation_ratio",
            ]
        ]
        .copy()
    )

    frequency = (
        selected_92.groupby(
            [
                "selected_C",
                "selected_gamma",
                "selected_epsilon",
            ]
        )
        .size()
        .reset_index(
            name="count"
        )
        .sort_values(
            [
                "count",
                "selected_C",
            ],
            ascending=[
                False,
                True,
            ],
        )
        .reset_index(
            drop=True
        )
    )

    # Boundary-selection diagnostics.
    C_upper_count = int(
        np.sum(
            selected_92[
                "selected_C"
            ]
            == max(
                SVR_C_VALUES
            )
        )
    )

    C_lower_count = int(
        np.sum(
            selected_92[
                "selected_C"
            ]
            == min(
                SVR_C_VALUES
            )
        )
    )

    gamma_lower_count = int(
        np.sum(
            selected_92[
                "selected_gamma"
            ]
            == min(
                SVR_GAMMA_VALUES
            )
        )
    )

    gamma_upper_count = int(
        np.sum(
            selected_92[
                "selected_gamma"
            ]
            == max(
                SVR_GAMMA_VALUES
            )
        )
    )

    epsilon_lower_count = int(
        np.sum(
            selected_92[
                "selected_epsilon"
            ]
            == min(
                SVR_EPSILON_VALUES
            )
        )
    )

    epsilon_upper_count = int(
        np.sum(
            selected_92[
                "selected_epsilon"
            ]
            == max(
                SVR_EPSILON_VALUES
            )
        )
    )

    # Save.
    seed_metrics_path = (
        args.output_root
        / "information_seed_metrics.csv"
    )

    paired_seed_path = (
        args.output_root
        / "information_paired_seed_results.csv"
    )

    summary_path = (
        args.output_root
        / "information_metric_summary.csv"
    )

    paired_stats_path = (
        args.output_root
        / "information_paired_statistics.csv"
    )

    candidates_path = (
        args.output_root
        / "oracle92_svr_candidates.csv"
    )

    selected_path = (
        args.output_root
        / "oracle92_selected_hyperparameters.csv"
    )

    frequency_path = (
        args.output_root
        / "oracle92_hyperparameter_frequency.csv"
    )

    damage_path = (
        args.output_root
        / "oracle92_damage_bins.csv"
    )

    report_path = (
        args.output_root
        / "information_repeated_split_report.json"
    )

    frame_92.to_csv(
        seed_metrics_path,
        index=False,
    )

    paired_seed_frame.to_csv(
        paired_seed_path,
        index=False,
    )

    summary_frame.to_csv(
        summary_path,
        index=False,
    )

    paired_stats_frame.to_csv(
        paired_stats_path,
        index=False,
    )

    candidates_frame.to_csv(
        candidates_path,
        index=False,
    )

    selected_92.to_csv(
        selected_path,
        index=False,
    )

    frequency.to_csv(
        frequency_path,
        index=False,
    )

    damage_frame.to_csv(
        damage_path,
        index=False,
    )

    report = {
        "experiment": (
            "10_seed_78D_vs_92D_RBF_SVR"
        ),
        "question": (
            "information availability under fixed estimator family"
        ),
        "seeds": SEEDS,
        "split_reuse": (
            "Exact split NPZ files from "
            "repeated_split_78d_ridge_svr"
        ),
        "canonical_alignment_passed": True,
        "78d_results_reused": str(
            args.reference_78d_metrics
        ),
        "92d_feature_count": (
            EXPECTED_92D_FEATURE_COUNT
        ),
        "selection_criterion": (
            "clipped validation MSE"
        ),
        "prediction_clip": [
            0.0,
            0.5,
        ],
        "svr_search_space": {
            "C": SVR_C_VALUES,
            "gamma": (
                SVR_GAMMA_VALUES
            ),
            "epsilon": (
                SVR_EPSILON_VALUES
            ),
            "candidate_count": (
                len(
                    SVR_C_VALUES
                )
                * len(
                    SVR_GAMMA_VALUES
                )
                * len(
                    SVR_EPSILON_VALUES
                )
            ),
        },
        "92d_boundary_selection_counts": {
            "C_lower": C_lower_count,
            "C_upper": C_upper_count,
            "gamma_lower": (
                gamma_lower_count
            ),
            "gamma_upper": (
                gamma_upper_count
            ),
            "epsilon_lower": (
                epsilon_lower_count
            ),
            "epsilon_upper": (
                epsilon_upper_count
            ),
        },
        "statistical_note": (
            "Ten paired repeated holdout partitions "
            "reuse the same 3000 simulated cases. "
            "Effect sizes and paired consistency are "
            "primary; inferential p-values are supportive "
            "rather than evidence of independent experiments."
        ),
    }

    with report_path.open(
        "w",
        encoding="utf-8",
    ) as file:
        json.dump(
            report,
            file,
            indent=2,
            ensure_ascii=False,
        )

    # Console output.
    print()
    print(
        "===== SEED-BY-SEED INFORMATION RESULTS ====="
    )

    display_seed = (
        paired_seed_frame[
            [
                "seed",
                "78d_test_mae",
                "92d_test_mae",
                "relative_improvement_percent_test_mae",
                "78d_high_damage_mae",
                "92d_high_damage_mae",
                "relative_improvement_percent_high_damage_mae",
                "78d_high_damage_underestimation_ratio",
                "92d_high_damage_underestimation_ratio",
            ]
        ]
    )

    print(
        display_seed.to_string(
            index=False,
            float_format=lambda x: (
                f"{x:.10f}"
            ),
        )
    )

    print()
    print(
        "===== AGGREGATE INFORMATION METRICS ====="
    )

    print(
        summary_frame.loc[
            summary_frame[
                "metric"
            ].isin(
                [
                    "test_mae",
                    "test_rmse",
                    "damaged_entry_mae",
                    "high_damage_mae",
                    "high_damage_abs_bias",
                    "high_damage_underestimation_ratio",
                ]
            )
        ][
            [
                "descriptor_set",
                "metric",
                "mean",
                "std",
                "ci95_low",
                "ci95_high",
            ]
        ].to_string(
            index=False,
            float_format=lambda x: (
                f"{x:.10f}"
            ),
        )
    )

    print()
    print(
        "===== PAIRED INFORMATION COMPARISON ====="
    )

    print(
        paired_stats_frame[
            [
                "metric",
                "78d_mean",
                "92d_mean",
                "mean_difference",
                "ci95_difference_low",
                "ci95_difference_high",
                "92d_wins",
                "78d_wins",
                "mean_relative_improvement_percent",
                "paired_t_pvalue",
                "wilcoxon_pvalue",
            ]
        ].to_string(
            index=False,
            float_format=lambda x: (
                f"{x:.10f}"
            ),
        )
    )

    print()
    print(
        "===== 92D SELECTED HYPERPARAMETERS ====="
    )

    print(
        selected_92.to_string(
            index=False,
            float_format=lambda x: (
                f"{x:.10f}"
            ),
        )
    )

    print()
    print(
        "===== 92D HYPERPARAMETER FREQUENCY ====="
    )

    print(
        frequency.to_string(
            index=False,
        )
    )

    print()
    print(
        "===== 92D BOUNDARY-SELECTION COUNTS ====="
    )

    print(
        "C lower:",
        C_lower_count,
    )

    print(
        "C upper:",
        C_upper_count,
    )

    print(
        "Gamma lower:",
        gamma_lower_count,
    )

    print(
        "Gamma upper:",
        gamma_upper_count,
    )

    print(
        "Epsilon lower:",
        epsilon_lower_count,
    )

    print(
        "Epsilon upper:",
        epsilon_upper_count,
    )

    print()
    print(
        "===== INTEGRITY CHECKS ====="
    )

    print(
        "Canonical 78D/92D targets aligned:",
        True,
    )

    print(
        "Frozen 78D result count:",
        len(
            reference_78
        ),
    )

    print(
        "Split files reused:",
        len(
            SEEDS
        ),
    )

    print(
        "92D seeds completed:",
        frame_92[
            "seed"
        ].nunique(),
    )

    print(
        "Per-seed 92D scaling:",
        True,
    )

    print(
        "Same frozen 75-candidate grid:",
        True,
    )

    print()
    print(
        "CHECK PASSED: 10-seed "
        "78D-vs-92D SVR information "
        "comparison completed."
    )

    print(
        "Paired statistics:",
        paired_stats_path,
    )

    print(
        "Report:",
        report_path,
    )


if __name__ == "__main__":
    main()
