"""
File location:
    src/data_generation/inspect_npz.py

Purpose:
    Inspect the content of a .npz file generated by OpenSeesPy.

中文说明：
    用于查看 OpenSeesPy 生成的 .npz 数据文件中到底保存了哪些数组。
    .npz 是二进制压缩文件，不能直接用 VS Code 文本编辑器查看。
    正确方式是用 numpy.load() 读取。
"""

from __future__ import annotations
# 延迟类型注解的解析，保持代码兼容性和可读性。

import argparse
# argparse 用于从命令行读取参数，例如用户指定 .npz 文件路径。

from pathlib import Path
# Path 用于处理文件路径，比直接写字符串更安全。

import numpy as np
# numpy 用于读取 .npz 文件和处理数组。


def describe_array(name: str, array: np.ndarray) -> None:
    """
    Print basic information of one NumPy array.

    中文说明：
        打印某一个数组的基本信息：
        1. 数组名称；
        2. 形状 shape；
        3. 数据类型 dtype；
        4. 最小值、最大值、均值；
        5. 是否存在 NaN 或 Inf。
    """

    arr = np.asarray(array)
    # np.asarray() 将输入转换为 NumPy 数组。
    # 如果输入本来就是 NumPy 数组，则基本不会额外复制。

    print(f"\nArray name: {name}")
    # 打印数组名称。

    print(f"  shape: {arr.shape}")
    # shape 表示数组维度。
    # 例如 (2000, 4) 表示 2000 个时间步、4 个楼层。

    print(f"  dtype: {arr.dtype}")
    # dtype 表示数组的数据类型，例如 float64、int64。

    if arr.size == 0:
        # arr.size 表示数组元素总数。
        # 如果数组为空，则不继续计算统计量。
        print("  empty array")
        return

    if np.issubdtype(arr.dtype, np.number):
        # np.issubdtype 用来判断数组是不是数值类型。
        # 只有数值数组才计算 min/max/mean。

        print(f"  min: {np.nanmin(arr)}")
        # np.nanmin 忽略 NaN 后计算最小值。

        print(f"  max: {np.nanmax(arr)}")
        # np.nanmax 忽略 NaN 后计算最大值。

        print(f"  mean: {np.nanmean(arr)}")
        # np.nanmean 忽略 NaN 后计算均值。

        print(f"  has_nan: {np.isnan(arr).any()}")
        # 检查是否存在 NaN。

        print(f"  has_inf: {np.isinf(arr).any()}")
        # 检查是否存在 Inf。

    else:
        print("  non-numeric array")
        # 如果不是数值数组，不计算统计量。


def inspect_npz(npz_path: Path) -> None:
    """
    Load and inspect a .npz file.

    中文说明：
        读取 .npz 文件，并逐个打印其中数组的信息。
    """

    if not npz_path.exists():
        # 检查路径是否存在。
        raise FileNotFoundError(f"File not found: {npz_path}")

    data = np.load(npz_path, allow_pickle=False)
    # np.load() 用于读取 .npy 或 .npz 文件。
    # allow_pickle=False 更安全，避免加载不必要的 Python 对象。

    print(f"Loaded file: {npz_path}")
    # 打印当前读取的文件路径。

    print(f"Keys: {list(data.keys())}")
    # data.keys() 是 .npz 文件里保存的所有数组名称。

    for key in data.keys():
        # 遍历每一个数组名称。
        describe_array(key, data[key])
        # 打印该数组的详细信息。


def main() -> None:
    """
    Command-line entry point.

    中文说明：
        命令行入口函数。
        允许你在终端中运行：
        python -m src.data_generation.inspect_npz data_raw/opensees_outputs/demo_damage_case.npz
    """

    parser = argparse.ArgumentParser()
    # 创建命令行参数解析器。

    parser.add_argument(
        "npz_path",
        type=str,
        help="Path to the .npz file to inspect.",
    )
    # 添加一个必须输入的位置参数：npz_path。

    args = parser.parse_args()
    # 解析命令行输入。

    inspect_npz(Path(args.npz_path))
    # 调用主检查函数。


if __name__ == "__main__":
    # 只有直接运行这个文件时才执行 main()。
    main()
